#! /usr/bin/env ruby

require 'unsplash'
require 'process_helper'

include ProcessHelper

Unsplash.configure do |config|    
  config.application_id     = ""    
  config.application_secret = ""
  config.application_redirect_uri = "urn:ietf:wg:oauth:2.0:oob"
end

splash = Unsplash::Photo.random

file_name = Time.now.to_i

# get image
process("wget --quiet #{splash.urls.raw} -O /tmp/#{file_name}")

# set image
process("sqlite3 ~/Library/Application\\ Support/Dock/desktoppicture.db \"update data set value = '/tmp/#{file_name}'\";")
process("killall Dock;")

